# Generated by Django 3.1.7 on 2021-03-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_id',
            field=models.IntegerField(null=True),
        ),
    ]
